# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-25 09:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gait_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30, verbose_name='昵称')),
                ('role', models.CharField(choices=[('1', '普通用户'), ('2', '管理员')], max_length=1, verbose_name='用户角色')),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='体重')),
                ('height', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='身高')),
                ('sex', models.CharField(choices=[('M', '男'), ('F', '女')], default='M', max_length=2, verbose_name='性别')),
                ('birthday', models.IntegerField(blank=True, null=True, verbose_name='出生年份')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户信息表',
                'verbose_name_plural': '用户信息表',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='token')),
                ('expire', models.BigIntegerField(verbose_name='expire')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户令牌',
                'verbose_name_plural': '用户令牌',
            },
        ),
        migrations.CreateModel(
            name='User_role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.SmallIntegerField(default=1)),
                ('role_name', models.CharField(default='普通用户', max_length=30, verbose_name='用户角色')),
            ],
            options={
                'verbose_name': '角色表',
                'verbose_name_plural': '角色表',
            },
        ),
    ]
