# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-25 09:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acceleration_l_foot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=30, verbose_name='device_id')),
                ('index_id', models.IntegerField(db_index=True, verbose_name='index_id')),
                ('timestamp', models.BigIntegerField(verbose_name='timestamp')),
                ('acc_l_x', models.SmallIntegerField(verbose_name='acc_l_x')),
                ('acc_l_y', models.SmallIntegerField(verbose_name='acc_l_y')),
                ('acc_l_z', models.SmallIntegerField(verbose_name='acc_l_z')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '左加速度',
                'verbose_name': '左加速度',
            },
        ),
        migrations.CreateModel(
            name='Acceleration_r_foot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=30, verbose_name='device_id')),
                ('index_id', models.IntegerField(db_index=True, verbose_name='index_id')),
                ('timestamp', models.BigIntegerField(verbose_name='timestamp')),
                ('acc_r_x', models.SmallIntegerField(verbose_name='acc_r_x')),
                ('acc_r_y', models.SmallIntegerField(verbose_name='acc_r_y')),
                ('acc_r_z', models.SmallIntegerField(verbose_name='acc_r_z')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '右加速度',
                'verbose_name': '右加速度',
            },
        ),
        migrations.CreateModel(
            name='Gyroscope_l_foot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=30, verbose_name='device_id')),
                ('index_id', models.IntegerField(db_index=True, verbose_name='index_id')),
                ('timestamp', models.BigIntegerField(verbose_name='timestamp')),
                ('gyro_l_x', models.SmallIntegerField(verbose_name='gyro_l_x')),
                ('gyro_l_y', models.SmallIntegerField(verbose_name='gyro_l_y')),
                ('gyro_l_z', models.SmallIntegerField(verbose_name='gyro_l_z')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '左角速度',
                'verbose_name': '左角速度',
            },
        ),
        migrations.CreateModel(
            name='Gyroscope_r_foot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=30, verbose_name='device_id')),
                ('index_id', models.IntegerField(db_index=True, verbose_name='index_id')),
                ('timestamp', models.BigIntegerField(verbose_name='timestamp')),
                ('gyro_r_x', models.SmallIntegerField(verbose_name='gyro_r_x')),
                ('gyro_r_y', models.SmallIntegerField(verbose_name='gyro_r_y')),
                ('gyro_r_z', models.SmallIntegerField(verbose_name='gyro_r_z')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '右角速度',
                'verbose_name': '右角速度',
            },
        ),
        migrations.CreateModel(
            name='Pressure_l_foot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=30, verbose_name='device_id')),
                ('index_id', models.IntegerField(db_index=True, verbose_name='index_id')),
                ('timestamp', models.BigIntegerField(verbose_name='timestamp')),
                ('pre_l_a', models.SmallIntegerField(verbose_name='pre_l_a')),
                ('pre_l_b', models.SmallIntegerField(verbose_name='pre_l_b')),
                ('pre_l_c', models.SmallIntegerField(verbose_name='pre_l_c')),
                ('pre_l_d', models.SmallIntegerField(verbose_name='pre_l_d')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '左压力',
                'verbose_name': '左压力',
            },
        ),
        migrations.CreateModel(
            name='Pressure_r_foot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=30, verbose_name='device_id')),
                ('index_id', models.IntegerField(db_index=True, verbose_name='index_id')),
                ('timestamp', models.BigIntegerField(verbose_name='timestamp')),
                ('pre_r_a', models.SmallIntegerField(verbose_name='pre_r_a')),
                ('pre_r_b', models.SmallIntegerField(verbose_name='pre_r_b')),
                ('pre_r_c', models.SmallIntegerField(verbose_name='pre_r_c')),
                ('pre_r_d', models.SmallIntegerField(verbose_name='pre_r_d')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '右压力',
                'verbose_name': '右压力',
            },
        ),
        migrations.CreateModel(
            name='Signal_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_strength', models.IntegerField(verbose_name='signal_strength')),
                ('timestamp', models.BigIntegerField(verbose_name='timestamp')),
            ],
            options={
                'verbose_name_plural': '信号强度',
                'verbose_name': '信号强度',
            },
        ),
        migrations.CreateModel(
            name='Sta_index',
            fields=[
                ('sta_index', models.AutoField(primary_key=True, serialize=False, verbose_name='sta_index')),
                ('device_id', models.CharField(max_length=30, verbose_name='device_id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Statistics_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_id', models.IntegerField(unique=True, verbose_name='index_id')),
                ('start_time', models.BigIntegerField(verbose_name='start_time')),
                ('end_time', models.BigIntegerField(verbose_name='end_time')),
                ('steps', models.IntegerField(verbose_name='steps')),
                ('velocity', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='velocity')),
                ('velocity_max', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='max_velocity')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='distance')),
                ('cadence', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='cadence')),
                ('stance_time', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='stance_time')),
                ('swing_time', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='swing_time')),
                ('l_step_length', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='l_steps_length')),
                ('r_step_length', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='r_steps_length')),
                ('double_s_time', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='double_s_time')),
                ('calorie', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='calorie')),
                ('acceleration_time', models.IntegerField(verbose_name='acceleration_time')),
                ('deceleration_time', models.IntegerField(verbose_name='deceleration_time')),
            ],
            options={
                'verbose_name_plural': '统计信息',
                'verbose_name': '统计信息',
            },
        ),
        migrations.CreateModel(
            name='Subscribe_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribe_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribe_from', to='user_management.Gait_user', verbose_name='订阅自')),
                ('subscribe_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribe_to', to='user_management.Gait_user', verbose_name='订阅到')),
            ],
            options={
                'verbose_name_plural': '订阅信息',
                'verbose_name': '订阅信息',
            },
        ),
        migrations.CreateModel(
            name='Trace_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_id', models.IntegerField(db_index=True, verbose_name='index_id')),
                ('x', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='x')),
                ('y', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='y')),
                ('v', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='velocity')),
            ],
            options={
                'verbose_name_plural': '轨迹信息',
                'verbose_name': '轨迹信息',
            },
        ),
    ]
